### ISSUE TITLE
Consider creating a first release?

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/membership_entity#1]
👋🏽 Hi @jayelless . This looks like a great module. Would you consider doing a release (even if it's an alpha) so that it gets listed among the Backdrop modules through the b.org module portal? I've been doing some light usage of it and everything seems to be working great.

**Comment by jayelless** [comment]
Hi Alejandro.

Thanks for your kind comments.  I have been trying to find time to get 
back to complete the conversion of this module, but have not yet been 
able to make that happen. However, I would like to get it done early in 
the new year.

Thank you also for your note about uninstalling the view.  I will add 
that functionality when I finish the module.

Regards,
James

**Comment by jayelless** [comment]
Initial release create.
