### ISSUE TITLE
Remove membership_entity_memberships view upon unistall

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/membership_entity#2]
The view membership_entity_memberships is left in the system after uninstalling membership_entity. Uninstalling modules doesn't seem to remove the views they created (perhaps this could be an issue in the main Backdrop queue).

To remove I suggest adding this to your uninstall hook in the .install file

```php
  $config = config('views.view.membership_entity_memberships');
  $config->delete();
```

**Comment by laryn** [comment]
The view config file should contain a line tying it to the module, I think, e.g.

```
"module": "membership_entity",
```

This may automate the removal of the view upon uninstallation.

**Comment by argiepiano** [comment]
> ```
> "module": "membership_entity",
> ```
> 
> 
>     
>   
> 
> This may automate the removal of the view upon uninstallation.

Great tip! I was not aware of this.

**Comment by jayelless** [comment]
Thanks for the tip. The "module" key has been added to the json file.
