### ISSUE TITLE
Update Readme File

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/membership_entity#3]
Thanks for the work on this module. It's much appreciated. 

I'm just noticing that the Readme file does not contain maintainer info. It would be good to get that updated. All contrib modules are supposed to include maintainer info in the Readme file.

https://github.com/backdrop-ops/contrib

"All projects must meet these minimum requirements." ... "Include a README.md file that includes license and maintainer information. You can use this example (https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md)."

**Comment by jayelless** [comment]
Missing information added to the README file.
